services:
  app:
    build: .
#    ports:
#      - '${PORT}:${PORT}'
    volumes:
       - ./app.js:/usr/src/app/app.js
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
